### ISSUE TITLE
PyTorch UT regression (2/2)

### ISSUE THREAD

**Issue by guangyey** [intel/intel-xpu-backend-for-triton#2585]
[TL,DR]
The following case is a PyTorch UT reproducer. It has regression with the commit b6cdccd33d901a2c187719e976e0aed026ea23f0 compared with 91b14bf5593cf58a8541f3e6b9125600a867d4ef. It means that `buf4` has more `NaN` value with the newer commit b6cdccd33d901a2c187719e976e0aed026ea23f0.
This impacts PyTorch upstream update triton commit pin, see https://github.com/pytorch/pytorch/pull/137886. The original PyTorch Inductor UT failure log is [here](https://github.com/pytorch/pytorch/actions/runs/11546764833/job/32136863571#step:14:2550)
Please help take a look.

```python
# AOT ID: ['0_inference']
from ctypes import c_void_p, c_long, c_int
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile
from torch._inductor.codegen.memory_planning import _align as align
from torch import device, empty_strided
from torch._inductor.async_compile import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels
from torch._inductor.codegen.multi_kernel import MultiKernelCall
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid, split_scan_grid, grid_combo_kernels, start_graph, end_graph
from torch._C import _xpu_getCurrentRawStream as get_raw_stream

aten = torch.ops.aten
inductor_ops = torch.ops.inductor
_quantized = torch.ops._quantized
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
empty_strided_cpu = torch._C._dynamo.guards._empty_strided_cpu
empty_strided_cuda = torch._C._dynamo.guards._empty_strided_cuda
empty_strided_xpu = torch._C._dynamo.guards._empty_strided_xpu
reinterpret_tensor = torch._C._dynamo.guards._reinterpret_tensor
alloc_from_pool = torch.ops.inductor._alloc_from_pool
async_compile = AsyncCompile()


# kernel path: /tmp/torchinductor_pt-gpu/ma/cmahji2k5z66bi2z4ydmruvxyprxadyepv7rylb2avg36ig5tsep.py
# Topologically Sorted Source Nodes: [div, div_1, div_2, truediv, floordiv], Original ATen: [aten.div, aten.floor_divide]
# Source node to ATen node mapping:
#   div => div
#   div_1 => div_1
#   div_2 => div_2
#   floordiv => div_4
#   truediv => div_3
# Graph fragment:
#   %div : [num_users=1] = call_function[target=torch.ops.aten.div.Tensor_mode](args = (%arg1_1, %arg2_1), kwargs = {rounding_mode: None})
#   %div_1 : [num_users=1] = call_function[target=torch.ops.aten.div.Tensor_mode](args = (%arg1_1, %arg2_1), kwargs = {rounding_mode: floor})
#   %div_2 : [num_users=1] = call_function[target=torch.ops.aten.div.Tensor_mode](args = (%arg1_1, %arg2_1), kwargs = {rounding_mode: trunc})
#   %div_3 : [num_users=1] = call_function[target=torch.ops.aten.div.Tensor](args = (%arg1_1, %arg2_1), kwargs = {})
#   %div_4 : [num_users=1] = call_function[target=torch.ops.aten.div.Tensor_mode](args = (%arg1_1, %arg2_1), kwargs = {rounding_mode: floor})
triton_poi_fused_div_floor_divide_0 = async_compile.triton('triton_poi_fused_div_floor_divide_0', '''
import triton
import triton.language as tl
from triton.compiler.compiler import AttrsDescriptor

from torch._inductor.runtime import triton_helpers, triton_heuristics
from torch._inductor.runtime.triton_helpers import libdevice, math as tl_math
from torch._inductor.runtime.hints import AutotuneHint, ReductionHint, TileHint, DeviceProperties
triton_helpers.set_driver_to_gpu()

@triton_heuristics.pointwise(
    size_hints=[16384], 
    filename=__file__,
    triton_meta={'signature': {'in_ptr0': '*i64', 'in_ptr1': '*i64', 'out_ptr0': '*fp32', 'out_ptr1': '*i64', 'out_ptr2': '*i64', 'out_ptr3': '*fp32', 'out_ptr4': '*i64', 'xnumel': 'i32'}, 'device': DeviceProperties(type='xpu', index=0, cc={'driver_version': '1.3.30049+10', 'gpu_eu_count': 512, 'gpu_subslice_count': 64, 'has_atomic64': True, 'has_bfloat16_conversions': True, 'has_fp16': True, 'has_fp64': True, 'has_subgroup_2d_block_io': True, 'has_subgroup_matrix_multiply_accumulate': True, 'has_subgroup_matrix_multiply_accumulate_tensor_float32': False, 'max_compute_units': 512, 'max_num_sub_groups': 64, 'max_work_group_size': 1024, 'name': 'Intel(R) Data Center GPU Max 1550', 'platform_name': 'Intel(R) oneAPI Unified Runtime over Level-Zero', 'sub_group_sizes': [16, 32], 'total_memory': 68719476736, 'type': 'gpu', 'vendor': 'Intel(R) Corporation', 'version': '12.60.7'}, major=None, regs_per_multiprocessor=None, max_threads_per_multi_processor=None, multi_processor_count=None, warp_size=32), 'constants': {}, 'configs': [AttrsDescriptor.from_dict({'tt.divisibility': (0, 1, 2, 3, 4, 5, 6), 'tt.equal_to': ()})]},
    inductor_meta={'autotune_hints': set(), 'kernel_name': 'triton_poi_fused_div_floor_divide_0', 'mutated_arg_names': [], 'optimize_mem': True, 'no_x_dim': False, 'num_load': 2, 'num_reduction': 0, 'backend_hash': '34F060980A1DF3BCB565864363593D6D7A2A9C7CD7B287BF5E3901F592299F23', 'are_deterministic_algorithms_enabled': False, 'assert_indirect_indexing': True, 'autotune_local_cache': True, 'autotune_pointwise': True, 'autotune_remote_cache': None, 'force_disable_caches': False, 'dynamic_scale_rblock': True, 'max_autotune': False, 'max_autotune_pointwise': False, 'min_split_scan_rblock': 256, 'spill_threshold': 16, 'store_cubin': False},
    min_elem_per_thread=0
)
@triton.jit
def triton_poi_fused_div_floor_divide_0(in_ptr0, in_ptr1, out_ptr0, out_ptr1, out_ptr2, out_ptr3, out_ptr4, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp2 = tl.load(in_ptr1 + (x0), xmask)
    tmp1 = tmp0.to(tl.float32)
    tmp3 = tmp2.to(tl.float32)
    tmp4 = tmp1 / tmp3
    tmp5 = tl.where((tmp0 < 0) != (tmp2 < 0), tl.where(tmp0 % tmp2 != 0, tmp0 // tmp2 - 1, tmp0 // tmp2), tmp0 // tmp2)
    tmp6 = tmp0 // tmp2
    tl.store(out_ptr0 + (x0), tmp4, xmask)
    tl.store(out_ptr1 + (x0), tmp5, xmask)
    tl.store(out_ptr2 + (x0), tmp6, xmask)
    tl.store(out_ptr3 + (x0), tmp4, xmask)
    tl.store(out_ptr4 + (x0), tmp5, xmask)
''', device_str='xpu')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1, arg2_1 = args
    args.clear()
    s1 = arg0_1
    assert_size_stride(arg1_1, (s1, s1), (s1, 1))
    assert_size_stride(arg2_1, (s1, s1), (s1, 1))
    with torch.xpu._DeviceGuard(0):
        torch.xpu.set_device(0)
        buf0 = empty_strided_xpu((s1, s1), (s1, 1), torch.float32)
        buf1 = empty_strided_xpu((s1, s1), (s1, 1), torch.int64)
        buf2 = empty_strided_xpu((s1, s1), (s1, 1), torch.int64)
        buf3 = empty_strided_xpu((s1, s1), (s1, 1), torch.float32)
        buf4 = empty_strided_xpu((s1, s1), (s1, 1), torch.int64)
        # Topologically Sorted Source Nodes: [div, div_1, div_2, truediv, floordiv], Original ATen: [aten.div, aten.floor_divide]
        triton_poi_fused_div_floor_divide_0_xnumel = s1*s1
        stream0 = get_raw_stream(0)
        triton_poi_fused_div_floor_divide_0.run(arg1_1, arg2_1, buf0, buf1, buf2, buf3, buf4, triton_poi_fused_div_floor_divide_0_xnumel, grid=grid(triton_poi_fused_div_floor_divide_0_xnumel), stream=stream0)
        del arg1_1
        del arg2_1
    # buf3 has more NaN value
    print(buf3)
    return (buf0, buf1, buf2, buf3, buf4, )


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = 100
    arg1_1 = rand_strided((100, 100), (100, 1), device='xpu:0', dtype=torch.int64)
    arg2_1 = rand_strided((100, 100), (100, 1), device='xpu:0', dtype=torch.int64)
    fn = lambda: call([arg0_1, arg1_1, arg2_1])
    return print_performance(fn, times=times, repeat=repeat)


if __name__ == "__main__":
    from torch._inductor.wrapper_benchmark import compiled_module_main
    torch.manual_seed(0)
    compiled_module_main('None', benchmark_compiled_module)

```

**Comment by alexbaden** [comment]
@guangyey can you please quantify this:
```
# buf3 has more NaN value
```
how many more NaN values?

**Comment by alexbaden** [comment]
I was able to reproduce the upstream test locally:
```
Mismatched elements: 32 / 10000 (0.3%)
Greatest absolute difference: 470271300776 at index (0, 22)
Greatest relative difference: 1.0 at index (0, 0)
```
appears to be different from #2579

**Comment by alexbaden** [comment]
Actually I think the two commits referenced in #2579 should fix this as well:
```
inductor [('benchmarking.TritonBenchmarker.benchmark_gpu', 2), ('fxgraph_cache_miss', 1), ('benchmarking.TritonBenchmarker.triton_do_bench', 1), ('fxgraph_cache_hit', 1)]
aot_autograd [('total', 2), ('ok', 2)]
.
----------------------------------------------------------------------
Ran 1 test in 6.168s

OK
```

**Comment by guangyey** [comment]
Thanks @alexbaden

**Comment by arunjose696** [comment]
Among the original unit test failures in pytorch, could observe the below test still fails with the merged commits as the result tensors are still different.

```
python test/inductor/test_torchinductor_dynamic_shapes.py DynamicShapesGPUTests.test_div7_dynamic_shapes_xpu
```

The other failed test (`DynamicShapesGPUTests.test_logcumsumexp_dynamic_shapes_xpu`) passes. The reproducer given in the issue fails with a different error. 

```
File "/home/jovyan/fork3/intel-xpu-backend-for-triton/python/triton/backends/compiler.py", line 167, in from_dict
    attrs_descriptor = _descriptor_table[data["cls"]]()
KeyError: 'cls'
```

would it be possible to create a PyTorch UT reproducer for `DynamicShapesGPUTests.test_div7_dynamic_shapes_xpu` which has the  value mismatch?

**Comment by arunjose696** [comment]
When checking at my end the pytest(`test/inductor/test_torchinductor_dynamic_shapes.py DynamicShapesGPUTests.test_div7_dynamic_shapes_xpu`) passes for https://github.com/intel/intel-xpu-backend-for-triton/commit/b6cdccd33d901a2c187719e976e0aed026ea23f0. And I can see failure on the latest main. While iterating over commits to find issue. I could see the issue seems to be intermittent with commits. At my end I can see the test passing for a few commits and failing for others.

```
Commit b6cdccd33d901a2c187719e976e0aed026ea23f0 passed
Commit 24e53d23022b449e75a5b6ec71515abb60e915ea failed
Commit 076a001dc76c6cbd9fa35dd201f64068d3494688 failed
Commit 25a7cbad82beb0d81283263d3d3885174bd290b3 failed
Commit 6d95f24e2d182e791e8c2473aac677a1b3395168 failed
Commit d16ef819a90c73cd6cf7816455fc780eaff543e7 failed
Commit 3ffaa2f250b1da457311a8dfda7c612cf7c565af failed
Commit c44a95bf2858ac7e173507e3cf5bd736a31980fa passed
Commit a626ab85bf2d09a0c385ced9ca50171a1fc3166c failed
Commit bbba43a9c3cef8781bec8a0824c5ec4c855f5bd4 failed
Commit af152a535e766afc0fe7ecb0dc6556eb7770f411 passed
Commit b9bb4d705a52213af8a2aee53d0e416c6c6c32c4 passed
Commit c6e60f0f7681604b1c5ed00a38f95869ec8c90fb passed
Commit a9ca5f0805c64452d0b9e149a690a0696476dba1 failed
Commit 6293c4b9f1e0d302b3b2d4880b6f7548ff4158b9 passed
Commit a3adef5ab52c9bff8e698968fbbc3bf8a88386ed passed
Commit 2beff56d3ad1c0f66e5b5574431a65923b189738 passed
Commit 5529b8798ee04eb740385a3cf9ab3f09202c8475 passed
Commit 61fd54d74ff1e3e5418db39cec8591d71dd010fe passed
Commit 520b193ee3b41e81b87c4efd1fb4984b5680644c passed
Commit 7e594865893eaf389541067b91ff60236b7788df passed
Commit 0f002cd9b2cd4e3ee2aecc7883ca803edafc606c passed
Commit d84531cd48e6dea1f7307141bf9c2671660aee13 passed
```

**Comment by alexbaden** [comment]
@arunjose696  `test_div7_dynamic_shapes_xpu` is passing for me with triton commit 0d9c0d3e09857d4b59038819b05db882090a6399 and pytorch upstream https://github.com/pytorch/pytorch/commit/78a8f7f5c3541e2c7c560d9c2ca465be709d4d3c. 
```
» python ../pytorch/test/inductor/test_torchinductor_codegen_dynamic_shapes.py -k test_div7_dynamic_shapes_xpu                                                                                                                            
[WARNING] Failed to create Level Zero tracer: 2013265921
[WARNING] Failed to create Level Zero tracer: 2013265921
/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/testing.py:31: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn("Wall time is used instead of elapsed_time (not supported). "
WARNING:root:Wall time is used instead of elapsed_time (not supported). The timing measurements could be innacurate.
inline_call []
stats [('calls_captured', 5), ('unique_graphs', 1)]
inductor [('benchmarking.TritonBenchmarker.benchmark_gpu', 2), ('fxgraph_cache_miss', 1), ('benchmarking.TritonBenchmarker.triton_do_bench', 1)]
aot_autograd [('total', 1), ('ok', 1)]
.
----------------------------------------------------------------------
Ran 1 test in 7.001s

OK
```

The `KeyError: 'cls'` is due to changes in the Inductor API between when the reproducer was generated and the current Inductor <-> Triton API. It can be fixed by modifying the `AttrsDescriptor` block to include an outer dictionary with an `arg_properties` key and a `cls` key.

**Comment by alexbaden** [comment]
@arunjose696 I ran the test several times in a loop and did notice several failures. After investigating further, I believe something has changed in the LLVM optimization pipeline which is changing the control flow for a divide operation and causing divide by 0 errors which create the incorrect results. I am at a loss for what has changed in the pass pipeline though - nothing has changed for us since Triton 3.1, and the generated LLVM MLIR looks correct. So, it might be something introduced in upstream LLVM. Will continue investigating tomorrow.

**Comment by alexbaden** [comment]
We resolved this temporarily in the release branch w/ https://github.com/intel/intel-xpu-backend-for-triton/commit/525afad4bc691649aa77253848229431f5cab83c

Closing as a duplicate of https://github.com/intel/intel-xpu-backend-for-triton/issues/2726 for the long term fix.

**Comment by guangyey** [comment]
Thanks very much~
